src/qtcore/qml/lib/jsparser.js

Introduces a condition, making our jsparse function use a globally defined "parse" function when run from a web browser, and requiring uglify-js when run by nodejs.
This change is required for the `gulp-qmlweb` package to work.

jsparser requires uglify-js if nodejs is detected

---

package.json

Explicitly listing files is one of two ways of overriding `.gitignore` if we put `lib/` there, another one would be to maintain an `.npmignore` that is equal to `.gitignore` minus the `lib/`, but that would be inconvenvient and would affect the `.gitignore` merges, perhaps.
This also ensures that no unexpected files are packaged (note that there are no directories listed, only glob patters with file extensions).
`tests` and `src` are packages purposely, I think that those should be always coupled with the built lib, also note that `src` could be used directly atm.
Including the `repository` field should give us a link to the repository, issues, and pull requests at the npm package page.

package.json improvements: explicitly list files, add repo field.

---

gulpfile.js
package.json

This uses `gulp-changed` to achive that.
Will be userful for writing (and testing) tests, because atm it consumes an extra 4 seconds on my notebook on the minification stage.

gulpfile: rebuild ./lib only if needed

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/Component.js
src/qtcore/qml/lib/jsparser.js
src/qtcore/qml/lib/parser.js
src/qtcore/qml/qml.js

I patched the code from master so that it would load modules and javascript imports using the qmlimport parser form kde-master, instead of the one currently in master (which was written by myself a long time ago, and shouldn't be kept, as it is less concise and doesn't conform to the parsing logic used everywhere else).
I also removed the import of QML files (such as: import my.qml), since I couldn't get it to work right away, and didn't find anything in the QML documentation about these kind of imports.
The only missing thing from import is the recursive import of a directory containing qml files. Could be done for node.js users, though for web browsers, we can only do it using the qrc thingy (since we can't access the filesystem). We may want to open a low priority issue to add that …

Parse import statements using kde-master's qmlimport

---

gulpfile.js
package.json

These are needed for various reasons, including debugging and (hopefully) coverage analysis.

gulpfile: Add sourcemaps.

---

src/qtcore/qml/qml.js

> The construct function overrided the inner context with some empty
context. This was due to an earlier misunderstanding of how the
contexts work and was completely meaningless (except of causing bugs).
I simply removed that line now.

Merge: Don't override inner component context.

---

.gitignore
README.md
gulpfile.js
karma.conf.js
package.json

This gives us crude coverage analysis.
It's based on a single file atm (`lib/qt.js`), that has to be fixed later.
Another related problem is that it also analyzes the bundled `uglify-js` code.
There are several ways of fixing that, but that could be done in follow-up PRs.
This (sort of) fixes #40.

Use karma, add Coveralls integration.

---

src/qtcore/qml/QMLBinding.js
src/qtcore/qml/lib/import.js
tests/QMLEngine/bindings.js
tests/QMLEngine/qml/BindingsNoSrc.qml

This makes the execution scope cleaner — `eval()` captures the parent scope, `new Function()` doesn't.
A testcase to ensure that `bindSrc` not being exported to the binding scope is included (fails on master).
/cc @Plaristote, @akreuzkamp

Reduce unneeded evals

---

gulpfile.js

Made some changes to the test gulp tasks:
* dont rebuild qt.min.js on every test build
* Karma seems to magically rebuild the qt.js file so i renamed karma to watch-tests and removed the latter (please verify)
* added chrome/chromium debugging

test task tweaks

---

tests/QMLEngine/javascript.js
tests/QMLEngine/qml/JavascriptRegexp.qml

Related to #58, improves our code coverage by checking that the code handling regexps in our js parser does the job.

adds a test to check that the js parser supports regexps

---

src/qtcore/qml/elements/QtQuick/SystemPalette.js
src/qtcore/qml/qml.js

The comment above `createSimpleProperty` spoke of an `options` parameter, which this commit now implements.
If the `options` parameter isn't an object, it'll be used as the default value. If it is an object, we look for the `readOnly` and `default` attributes to set the access policy and the default value.
This will fix the case(s?) when people have used the fourth parameter of `createSimpleProperty` to set default values (while this parameter was actually used to define the access policy).

adds an options parameter to createSimpleProperty

---

src/qtcore/qml/elements/QtQuick/TextInput.js

This is done instead of merging 8c6ec044d51cdd8cc19bd7e521616149bc4f6f09, because most part of that is already implemented in a different way.

TextInput: fallback to password for NoEcho, PasswordEchoOnEdit

---

src/qtcore/qml/elements/QtQuick/Image.js
tests/Render/Async/Image.qml

This is how Qt does things, it also gives us the correct dimensions inside the onStatusChanged callback.
The Image render tests has been modified to also check that the dimensions have been set correctly (it does not force them anymore).
/cc @Plaristote @akreuzkamp @henrikrudstrom

Image: set the status after dimensions

---

src/qtcore/qml/lib/parser.js
tests/QMLEngine/properties.js
tests/QMLEngine/qml/ItemWithPropertyNamedSignal.qml
tests/QMLEngine/qml/PropertiesNamedSignal.qml

So far if you wrote "signal:" as a property name the parsing would
fail because it handle signal as a keyword. Now this case is handled
that if signal is followed by a colon it's ok and handled as a
property.
This is completely untested, as I don't have a lot of time, these days. Please be so kind and add a auto test for me. :)
Fixes #76.

Fix parsing of properies named signal.

---

karma.conf.js
package.json
tests/QMLEngine/bindings.js
tests/QMLEngine/imports.js
tests/QMLEngine/javascript.js
tests/QMLEngine/properties.js
tests/QMLEngine/scope.js
tests/QtQuick/Item.js
tests/QtQuick/Rectangle.js
tests/Render/runner.js
tests/common.js

moved the `div` creating and removal code to `beforeEach` and `afterEach`
just add `setupDivElement();` to your test
```
describe('QMLEngine.scope', function() {
setupDivElement();
```

Refactor tests

---

src/qtcore/qml/elements/QtQuick/Repeater.js
tests/failingTests.js

This fixes the RepeaterNumber failing test.
Any comments on the TODO in the last commit?

Merge pavel repeater

---

src/qtcore/qml/QMLProperty.js
src/qtcore/qml/lib/parser.js
src/qtcore/signal.js
tests/QMLEngine/parse.js
tests/QMLEngine/qml/ParseError.qml

This is a rebased version of #28.
Merged commits: 79a05ff, f401c53, 7dad8e8, 44bea45.

Kde master ongoing merge — rebased

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/QtQuick/Font.js
src/qtcore/qml/elements/QtQuick/NumberAnimation.js
src/qtcore/qml/elements/QtQuick/Text.js
src/qtcore/qml/qml.js

This is actually a good change. You can't override `undefined` nowdays, so there is no use in saving it in a separate variable.

eliminate Undefined and replace references with undefined

---

tests/Render/Simple/RectangleBorder.qml
tests/Render/runner.js

There was an mistake where render tests were erroneously passing when they should fail.
That happened because `.getImageData()` was returning partial result (the image was not painted yet).
Also this fixes my merge error in the `RectangleBorder` render test.
/cc @henrikrudstrom @igosoft

Fix render tests

---

src/qtcore/qml/elements/Item.js
src/qtcore/qml/elements/QtQuick/Rectangle.js
tests/Initialize/runner.js

This uses inheritance to ensure that all QML DOM items will have `box-sizing: border-box`.
It also modified `Initialize` tests to check that.
See #90 and #110.

Set box-sizing: border-box on all Items

---

tests/QMLEngine/parse.js
tests/QMLEngine/qml/ParseFunctionVar.qml
tests/failingTests.js

this works in qt qml but not in webqml: 
`property var aFunction: function(){}`

test: cannot parse function assigned to var property

---

src/qtcore/qml/elements/QtQuick/Repeater.js

Manual `.parent` unsetting after `.$delete()` is not needed anymore due to 66222bc6cfb361c07602b8581ca21940a9309d14.
/cc @pavelvasev

Repeater: remove unneeded line

---

src/qmlweb/RestModel.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/QMLProperty.js
src/qtcore/qml/elements/Item.js
src/qtcore/qml/elements/QtQuick/NumberAnimation.js
src/qtcore/qml/elements/QtQuick/Repeater.js
src/qtcore/qml/qml.js

> During initialization it can happen that a property gets assigned a
> binding and later, still during init, gets assigned a constant value.
> In this case it wouldn't properly remove the binding and when later,
> during evaluating bindings phase, the constant value would get
> overwritten again, by the binding. This is not intended.
> 
> Now it's cleaned correctly.
Apart from one change, this merge was just about moving some code around.
Though I found a single line of code that still used the property setter function while using the `fromAnimation` parameter instead of the `reason` parameter introduced in this commit. It's the change I made to, `src/qtcore/qml/elements/Item.js`, using QMLProperty.ReasonUser as a parameter. I figured it was the right value to use in that context.

Merge "properly remove animations at overwriting on init."

---

gulpfile.js

This removes the `src/uglify/*` leftovers from the gulpfile (ref: #153) and merges `src/qtcore/*.js` into a single entry, they are all independant.
Note that `src/qtcore/*.js` is not the same as `src/qtcore/**/*.js` and is limited to a single level.

gulpfile: Cleanup qtcoreSources

---

src/qtcore/qml/elements/QtQuick/Repeater.js

Extracted from 2865c68cd7b5fc4865b8db474c1d9cc75eaf8c23.
Comment by @akreuzkamp:
> $tidyupList is a list of internal children (compare to QObject::children() in contrast to QQuickItem::children()!). It's called tidyupList because it's main use is to remove references to child objects when deleting an object. The whole concept of memory management QmlWeb uses so far is in great need of improvement.
In short: It passes on the Component.completed() signal to all it's children.
I still don't understand this completely, and this needs a review by someone.
/cc @akreuzkamp, @Plaristote, @pavelvasev

Repeater: pass on the Component.completed() signal to all children.

---

src/qtcore/qml/elements/QtQuick/MouseArea.js

See #49.
/cc @shry15harsh 
This doesn't support multiple buttons yet, but LGTM.
Multiple buttons are supported by Firefox, Chrome (since 43) and Edge nowdays, so this change could be extended to determine if `.buttons` is present and fallback to the implementation currently proposed by this PR.

Merge «Add property 'pressedButtons' to MouseArea»

---

src/qtcore/qml/lib/parser.js
tests/QMLEngine/parse.js

Prints the error like this:
```
1) QML TEST: SimpleRenderTest
Test.TestCase
Error: Unexpected token: punc (() (line: 6, col: 23, pos: 83)
3      id: test
4      delay: 200
5
>>6      startTest: function(){
7          test.compareRender("", function(equal){
8              expect(equal).toBe(true);
9              testDone();
(line 7)
JS_Parse_Error@/home/henrik/Development/qmlweb/lib/qt.js:9:167246
js_error@/home/henrik/Development/qmlweb/lib/qt.js:9:167557
...
...
```
Both lib/parser.js and uglify/parse.js defines `Js_Parse_Error` so i had to delete one, not sure which one.. this will be temporary until we resolve #140

print qml parse error in stacktrace

---

src/qtcore/qml/lib/import.js

Allows gulp-qmlweb to aggregate the qmldir files within the qrc object.
No changes required in gulp-qmlweb for this to work, although I'll update the README to have the default file matchers look like this:
```
var qmlFiles = [ 'qml/**/*.qml', 'qml/**/*.js', 'qml/**/qmldir' ];
```
This is all that's needed to make this work with gulp-qmlweb.

using qrc with readQmlDir to cache qmldir files

---

src/qtcore/qml/QMLBaseObject.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/Item.js
src/qtcore/qml/elements/QtQuick/Image.js
src/qtcore/qml/elements/QtQuick/Rectangle.js
src/qtcore/qml/elements/QtQuick/Text.js

This removes the remaining `.$draw()`, `.$drawItem()`, and `.$perfDraw()` methods.
Those were not used since the canvas renderer was removed.
/cc @Plaristote, @akreuzkamp.

Remove canvas backend leftovers

---

gulpfile.js

`QT_QPA_PLATFORM=xcb` is set by default in some systems now, e.g. Arch Linux, and that causes PhantomJS to fail.
Ref: https://github.com/ariya/phantomjs/issues/14061
This could be reverted after it gets fixed on PhantomJS side.

gulpfile: Clear QT_QPA_PLATFORM env var for PhantomJS to work

---

src/qtcore/qml/qml.js

Im not a big fan of failing silently, is there any reason not to throw more errors?

Throw error instead of logging when Qml constructor is not found

---

tests/QMLEngine/basic.js

This got missed in #171.
Perhaps we should make lint errors real errors on Travis, not just warnings.

tests: Fix an eslint long line warning

---

gulpfile.js
src/qtcore/qml/elements/QtQuick/Column.js
src/qtcore/qml/elements/QtQuick/Flow.js
src/qtcore/qml/elements/QtQuick/Grid.js
src/qtcore/qml/elements/QtQuick/ListView.js
src/qtcore/qml/elements/QtQuick/Positioner.js
src/qtcore/qml/elements/QtQuick/Row.js
src/qtcore/qml/qml.js

Implement string-based baseClass specification.
This allows to delay module registration until the base class is loaded.
This fixes the issue discussed here: https://github.com/qmlweb/qmlweb/pull/160#issuecomment-206384442 in a sane way, without forcing us to manually specify the element order in the gulpfile.
It currently also supports a short syntax, i.e. `Repeater` instead of `QtQuick.Repeater` when used from `QtQuick` module. Is it worth it, or does that just overcomplicate things?
Not all modules were converted to the new syntax yet, only those ones that failed without it.
Also this PR adds QmlWeb.Basic module, which I propose would include supportive classes to implement QtQuick modules, but which should not be present in QtQuick itself.
This would also be required to split modules …

Delay module registation until the base class is loaded.

---

src/qtcore/qml/QObject.js

Extracted from 4c3bcc649447c07401a53677b801c937d03779bb.
Note: I have not reviewed this code.
Note: `.destroy()` is used in RestModel for some reason.
Ref: #32.
/cc @pavelvasev @Plaristote @akreuzkamp

@pavelvasev merge: QObject: Add .destroy() method

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/Component.js
src/qtcore/qml/elements/Item.js
src/qtcore/qml/lib/jsparser.js
tests/QMLEngine/imports.js
tests/failingTests.js

* replace qmlEngine references with engine
* fix jsparser not properly walking the AST_Tree
* enable the QMLEngine JavascriptImport test
I noticed that js import wasn't working. Then I noticed the test was disabled. So I found what was blocking the test and fixed it (qmlEngine was used instead of engine in some place.... but qmlEngine is defined by the AutoLoader, and it's exclusively for use outside of qmlweb's scope. So I replaced the occurences of qmlEngine with engine).
Then I fixed a bug in jsparser, not properly using the AST_Tree returned by qmlparse.
The test was wrong as well: if we set a color to 'magenta', we shouldn't expect the CSS property to be 'magenta', but the rgb value for the magenta color (as this is the new behavior for QMLColor).

fix js import test not passing

---

tests/QMLEngine/properties.js
tests/QMLEngine/qml/PropertiesAliasChangedBack.qml
tests/failingTests.js

The changed signal of alias must call it's target property changed signal. Good for arrays modifications and manual changed invocation, when set is not used.
topic aliaschangeback at
https://github.com/qmlweb/qmlweb/issues/32#issuecomment-190834951

failing test case

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/qml.js
tests/failingTests.js

This merges 780450b635332ebd5182526b0123ad297c50fff1 and the aliases part of dce7d96.
Note: I have not reviewed this code.
Note: This fixes two testcases. It also blocks sorting out the two remaining changestets of #32, so it would be better to review this quickly =).
Ref: #32.
/cc @pavelvasev @Plaristote @akreuzkamp

@pavelvasev merge: Aliases now emit changes signals

---

src/qtcore/qml/elements/QtQuick/AnimatedImage.js

This is trivial, hoping for a quick review here.
This does not fix the `AnimatedImage` testcase just yet,  #200 (with more fixes) is required for that.

AnimatedImage: fix a mistype in constructor

---

.babelrc
src/qtcore/qml/lib/jsparser.js
src/qtcore/qt.js

The main change here is 00db7e0ede1ac09a796a7ca60904ae56287b8f55, the other two are minor fixes.
`Qt.Key_Yes` was defined twice, I removed a duplicate.
/cc @Plaristote

Remove outer eval in jsparser. Babelify everything but parser.js

---

tests/Initialize/runner.js

Dependencies are now optional (and working).
They were broken before, in `module._depends` `module` was actually a string.
Version is now included in the key. It's now possible to specify different sets of initialization tests per module per version.
And no more `_version`/`_depends` required!

tests: Simplify initialization tests

---

src/qtcore/qml/elements/QtQuick/Column.js
src/qtcore/qml/elements/QtQuick/Flow.js
src/qtcore/qml/elements/QtQuick/Grid.js
src/qtcore/qml/elements/QtQuick/Positioner.js
src/qtcore/qml/elements/QtQuick/Row.js
tests/failingTests.js

This fixes the zero opacity testcase mentioned in #185 and #191.
Merges 3b78802 and d53fefb.
Refs: #128.
LGTM.
/cc @igosoft, @Plaristote, @akreuzkamp

@igosoft merge: Do not hide zero-opacity items in positioners

---

src/qtcore/qml/qml.js

There is no need to return things from setters, those are not used — `a = b` always returns `b` (i.e. the value being assigned), returning anything from the setter does not affect that.
This merges abdc0e0adfd6529c6f6989a1a780845bfb628393, ref: #128.
LGTM, going to merge shortly.

@igosoft merge: Do not return values from property setters

---

tests/Initialize/runner.js

Also this adds an empty `'QtMobility 1.2'` initialize tests category, to remind us that we don't have any tests there.
/cc @henrikrudstrom, @Plaristote

tests: Add some more missing initialize tests

---

src/qtcore/qml/lib/jsparser.js

This is a follow-up to #214 that removes the remaining `eval()` and replaces it with code generation.
No more evals in code :wink:.
/cc @Plaristote

jsparser: Replace eval with codegen

---

gulpfile.js
src/qtcore/qml/lib/parser.js
src/qtcore/qml/lib/qmlstructure.js

This is the first step towards #173.
Basicaly, `parser.js` now exports only `qmlweb_parse`, everything else is internal.
Elements from `qmlstructure.js` and `QMLBinding` would be needed at runtime, `qmlweb_parse` (and everything else from `parser.js`) won't be, if the user would use pre-parsed files.
In future, everything but `parser.js` would be kept in the main repo, `parser.js` would be made a stand-alone library and an optional requirement (auto-loaded, though).
/cc @Plaristote, @akreuzkamp, @lpaimen.
@akreuzkamp, @lpaimen — could you confirm that I got the copyrights correct? There seems to be no code from UglifyJS in the new `qmlstructure.js`, please correct me if I'm wrong.

parser: Move QML runtime elements to qmlstructure.js

---

src/modules/QtQuick.Controls/Checkbox.js

This merges 6bbfa8301bfc06c5f29c5da6bd116df2300b62c9.
Ref: #32.
@pavelvasev, could you explain why this is needed and why is a value of 4 pixels hardcoded?
/cc @pavelvasev @Plaristote @akreuzkamp

@pavelvasev merge: CheckBox: fix implicitWidth

---

src/modules/QtQuick/Item.js

This is a cherry-pick of a339ee7, ref: #32.
Commit message:
> Root element resizing fixes
> 
> 1. window.onresize function is changed to addEventListener("resize")
call.
2. In case when qml scene is placed in some dom tag (case 2),
we have to call `self.implicitHeight =` and `self.implicitWidth =`
each time the rootElement changes it's geometry
to reposition child elements of qml scene
> Also there is a small note. Because in qmlweb implicitHeight= is chained
to updateHGeometry,
which in turn calls height=, which in turn sets element dom style, the
user have to set
rootElement's width/height css styles to !important.
Maybe it should be noted somewhere in the docs. This note is not
regarding to the current patch.
@pavelvasev What is the reason for storing the callback in …

@pavelvasev merge: Root element resizing fixes

---

src/qtcore/qml/QMLEngine.js

It seems that nothing does use this in @igosoft fork, so I am not sure if we need this.
~~Based on #193, review only the last commit here.~~ *Update: rebased on master instead*.
This is a cherry-pick of a6618d4bb56ffb97a75d12c02fc5cdea91e2bda6 with `loadQML` support added for consistency.
/cc @igosoft @Plaristote @akreuzkamp @pavelvasev
Refs: #128.

@igosoft merge: QMLEngine: return root component from load{File,QML,QMLTree}

---

src/qtcore/qml/qml.js

This merges commit 2308bcc, ref: #223.
We might need some more explanations on this, but this is likely related to loader per @igosoft comment.
/cc @igosoft, @akreuzkamp, @Plaristote.

@igosoft merge: move default property updates to the top in applyProperties

---

src/modules/QtQml/Component.js
src/qtcore/qml/qml.js

> if we create context for every createComponent call, maybe it is too
heavy... So we introduce option to provide context in createObject
method which overrides it's component context.
This merges 871fbf03c8dcdda039c5556add2bdfb1b2523c41, ref: #32.
/cc @pavelvasev @Plaristote

@pavelvasev merge: Component context optimization.. maybe we do not need it?

---

src/modules/QtQuick/ListModel.js

This merges commit 691330f, ref: #223.
This adds support for `append()`-ing an array of elements to `ListModel`, but somewhy doesn't add support for `insert()`-ing an array of elements. Qt QML supports both, afaik.
/cc @igosoft

@igosoft merge: ListModel updates

---

src/qtcore/qml/jsparser.js

.pragma statements are not currently respected, but they at least won't
cause the rest of the file to fail to import.

jsparser: Support importing JavaScript files with ".pragma" statements

---

src/qtcore/qml/QMLProperty.js

This is more inline with the C++ QML Engine that logs the error, but
continues working.

QMLProperty: Log thrown exceptions when evaluating a binding

---

LICENSE
src/qtcore/qml/import.js
src/qtcore/qml/qmlstructure.js

See #52.
I propose to do this asap, because any forks (we already have several new ones) would inherit the license.
/cc @akreuzkamp, @lpaimen, @pavelvasev for the first round of review (you are directly mentioned in the license).
`import.js` and `qmlstructure.js` go from BSD-2-Clause to MIT, everything else goes from modified BSD-3-Clause to MIT.
Parser has been already moved to a separate repo and is licensed under BSD-2-Clause.
I am not a lawyer, this kind of merging licenses is based on what I have seen elsewhere.
Another option would be to just write `Copyright (c) 2011-2016 QmlWeb contributors`, but I'm not exactly sure if that would be a correct change.

Relicense under MIT

---

src/modules/QtQuick/Repeater.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/QMLProperty.js
src/qtcore/qml/qml.js
src/qtcore/signal.js
tests/failingTests.js

merged recursive properties from @pavelvasev branch
@ChALkeR

@pavelvasev merge: Merge recursive props

---

src/modules/QtQml/Timer.js
tests/QtQuick/Timer.js
tests/QtQuick/qml/TimerRunning.qml

QML allows `Timer.running` to be set to start/stop a timer: http://doc.qt.io/qt-5/qml-qtqml-timer.html#running-prop
Currently, setting `running` to false works, but not setting `running` to true.

Timer set running explicitly

---

.travis.yml
gulpfile.js
karma.conf.js
package.json

This makes `npm test` much faster.
Coverage could be obtained by running `npm coverage`.

gulpfile: separate coverage task from test task

---

gulpfile.js
src/modules/QtQml/Component.js
src/modules/QtQml/Qt.js
src/modules/QtQuick/SystemPalette.js
src/qtcore/AutoLoader.js
src/qtcore/QMLBinding.js
src/qtcore/QMLEngine.js
src/qtcore/QMLOperationState.js
src/qtcore/QmlWeb.js
src/qtcore/import.js
src/qtcore/jsparser.js
src/qtcore/qml.js
src/qtcore/qmlstructure.js
src/qtcore/qrc.js
src/qtcore/signal.js
tests/QMLEngine/basic.js
tests/common.js
tests/qmlweb.js

Fixes: https://github.com/qmlweb/qmlweb/issues/51
We might want to add more methods/variables to the QmlWeb variable.
This does not deal with enums on a purpose, those should be covered by #271.
/cc @Plaristote @akreuzkamp @stephenmdangelo — PTAL.

Introduce QmlWeb variable, don't pollute global

---

src/engine/qml.js

This allows new custom QML Components to be defined in .js files outside
of lib/qt.js.

Export callSuper and createProperty via QmlWeb

---

src/engine/qml.js
tests/QMLEngine/basic.js
tests/QMLEngine/qml/BasicSignalParameters.qml

This was causing parameters in signals to not be accessible in slots.

engine/qml: Fix typo when creating declarative signals

---

gulpfile.js
src/engine/QMLBoolean.js
src/engine/QMLInteger.js
src/engine/QMLList.js
src/engine/QMLNumber.js
src/engine/QMLProperty.js
src/engine/QMLString.js
src/engine/QMLVariant.js
src/engine/qml.js
src/modules/QtQuick.Controls/Checkbox.js
src/modules/QtQuick/Rectangle.js
src/modules/QtQuick/Text.js
src/polyfills/WeakMap.js
src/qtbase/QColor.js
tests/QMLEngine/basic.js
tests/QtBase/QColor.js
tests/QtQml/Types.js
tests/QtQml/qml/TypesColor.qml

/cc @akreuzkamp @Plaristote @labsin 
The first commit is required to support initializing property types that require `new` usage (both «classes» and other prototype-based).
Creation of a `QColor` from an array was broken and not used.
Qt QML keeps the converted colors lower-case, testcase added.
`QColor` is not yet finished here, but it's already better than what we have now, and I think we should land this as is and continue improving it later.

QColor cleanup

---

src/qtbase/QColor.js

This adds a user-configurable limit of comparable colors to avoid the potential memory hit.
The limit is set to 10000 QColor instances, which should use about 200-300 KiB.
Refs: https://github.com/qmlweb/qmlweb/pull/307
/cc @akreuzkamp

QColor: introduce a limit to comparable colors

---

src/modules/QtQuick/Text.js
tests/QtQuick/Text.js
tests/QtQuick/qml/TextImplicitSize.qml

This is required as, once the size is set once, it will not be properly
re-calculated when any other property connected to "updateImplicit" is
changed, as the offsetWidth/offsetHeight will always return the current
size.

QtQuick/Text: Move span to document body before calculating implicit size

---

src/modules/QtQml/Timer.js
tests/QtQuick/Timer.js
tests/QtQuick/qml/TimerParentProperty.qml

C++ QML has the parent property explicitly defined for Timer components,
since Timer doesn't inherit from Item:
https://github.com/qt/qtdeclarative/blob/5.7.0/src/qml/types/qqmltimer_p.h#L72

Timer: Added parent property

---

src/modules/QtQuick/Item.js

With the change to giving Timer a read-only "parent" property, it was
no longer added to resources (and logged out exceptions).

QtQuick/Item: Only set "parent" property for Item-inherited items

---

src/modules/QtQuick/Loader.js

Parts of Loader got broken in commit 6f746cb5656e942ec94397fcf1b22df27354a8ca. Having not much competence in javascript / qmlweb, just copied related implementation from Repeater that seems to work better - at least for now.

Loader: fix callOnCompleted method

---

src/engine/QMLEngine.js
src/engine/qml.js
src/modules/QtQml/Component.js
src/modules/QtQml/Qt.js
src/modules/QtQuick/Loader.js
src/modules/QtQuick/Repeater.js
tests/QMLEngine/basic.js
tests/QMLEngine/qml/BasicCreateObject.qml
tests/QMLEngine/qml/BasicCreateObjectSomeComponent.qml
tests/Render/Simple/PropertyGrid.qml
tests/RenderQml/PropertyGridComponent.qml

This is an alternative approach to the issue, that #275 tries to fix.
This approach isn't very nice, either, but I consider it at least a bit better.
The issue I see with the other approach is that it sets `parent` (including all its consequences with inserting it into the dom, etc.) in `construct` just to override it later, in case it wasn't supposed to.

Component: set Item.parent in createObject - alternative

---

src/modules/QtQuick/MouseArea.js

This properly mimics QML's behaviour
@ChALkeR Any ideas on how to test this? From a quick Google search, it looks like we would have to use jQuery event handlers and .trigger to simulate events from within Jasmine, but maybe there's a better way.

MouseArea: Set pressed to false on release, even if outside of MouseArea

---

src/engine/QMLEngine.js
src/engine/QMLProperty.js
src/engine/qml.js
src/modules/QtQml/Component.js
src/modules/QtQml/Qt.js
src/modules/QtQuick/Item.js
src/modules/QtQuick/Loader.js
tests/QMLEngine/imports.js
tests/QMLEngine/qml/ImportFrom/LocalComponentProperty.qml
tests/QMLEngine/qml/ImportLocalComponentAsPropertyInAnotherDir.qml
tests/QMLEngine/qml/ImportLocalToFile/DirectoryFail.qml
tests/QMLEngine/qml/ImportLocalToFile/DirectoryFailSomeComponent.qml
tests/QMLEngine/qml/ImportLocalToFile/ModuleFail1.qml
tests/QMLEngine/qml/ImportLocalToFile/ModuleFail2.qml
tests/QMLEngine/qml/ImportLocalToFile/ModuleFailSomeComponent.qml
tests/QMLEngine/qml/ImportLocalToFile/ModuleSucceed.qml
tests/QMLEngine/qml/ImportLocalToFile/ModuleSucceedSomeComponent.qml
tests/QMLEngine/qml/ImportQualifiedModule.qml
tests/QMLEngine/qml/ImportQualifiedNoQmldir.qml
tests/QtQuick/qml/LoaderComponent.qml
tests/QtQuick/qml/LoaderDirectory/LoaderDirectoryComponent.qml

I have added tests that currently fail with master, but work with these changes.
There are still some uses (like in QMLProperty.set) that should be using the perImportContextConstructors, but it is checking for things like "QMLComponent" that are likely going to be imported into every file with "import QtQuick", so it's not really an issue.

Per import context constructors

---

src/engine/QMLEngine.js

No actual changes here, code style only.
IMO, it looks more readable this way.
/cc @stephenmdangelo

QMLEngine: simplify import path related code style

---

package.json
src/engine/qmlstructure.js

`qmlobjdef` supports only two components, a different format is needed to support assignments like `Drag.hotSpot.x: width / 2`.
Let's just use `qmlprop` with `name = 'Drag.hotSpot.x'` for that, instead of defining a separate token type for properties with two components.
After being merged here, a change on the parser side would be needed to support `Drag.hotSpot.x`.
Refs: https://github.com/qmlweb/qmlweb-parser/pull/17
/cc @akreuzkamp

qmlstructure: deprecate qmlobjdef, use qmlprop instead

---

src/qtbase/Signal.js
tests/QtBase/Signal.js

This implements `QueuedConnection` support, where actual execution of the signal handler is delayed until the control returns to the event loop.
/cc @akreuzkamp 
I am not sure if I did the correct thing with `QmlWeb.QMLProperty.pushEvalStack()` and `QmlWeb.QMLProperty.popEvalStack()`, so /cc @pavelvasev and @stephenmdangelo for that.

Signal: add QueuedConnection support

---

src/engine/QMLEngine.js

Should fix the problem of autoloading for example "./qml/index.qml" resulting in trying to load ./qml/qml/index.qml" instead.

QMLEngine: Fix loadFile to work with subdirectories

---

src/engine/properties.js
tests/QMLEngine/qml/PropertiesUrlDir/PropertiesUrlImport.qml

Slots can be invoked as the result of a property changing, and they
shouldn't leave the engine $basePath in a bad state.

engine/properties: Set engine $basePath back after evaluating a slot

---

src/engine/properties.js
tests/QMLEngine/properties.js
tests/QMLEngine/qml/PropertiesUrlDir/PropertiesUrlImportWithExceptions.qml
tests/QMLEngine/qml/PropertiesUrlExceptionSafe.qml

Previously, the $basePath could end up in a bad state if a slot threw an
exception.

properties/connectSignal: restore QmlEngine.$basePath on slot exception

---

src/engine/properties.js

Fixes an exception for properties named "on"
No longer check for a signal for properties like "on_" (since
"_".toUpperCase() === "_")
If no signal is found, try to find a property with the name
(for properties like "onProp" that match the RegExp).

engine/properties: Support properties starting with "on"

---

src/modules/QtQuick/MouseArea.js

QtQuick/MouseArea: set mouseX and mouseY before emitting positionChanged

---

src/modules/QtQuick/Text.js
tests/QtQuick/Text.js
tests/QtQuick/qml/TextWrapMode.qml

Call $onWrapModeChanged to initialize CSS properties for the default
wrapMode of NoWrap.
Also removed double connections to text, wrapMode changed.

modules/Text: Properly initialize wrapMode

---

examples/embed.html
src/engine/QMLEngine.js
src/modules/QtQuick/Item.js
tests/Initialize/runner.js
tests/QMLEngine/bindings.js
tests/QMLEngine/imports.js
tests/QtQuick/Item.js
tests/QtQuick/Rectangle.js

This is a breaking change, and it alters test expectations.
Before this change, all top-level QML elements were created in place of the DOM element passed to `QMLEngine(element)` constructor (let's call it «bounding element») and altered that element significantly, setting its width and height.
This PR only slightly changes the style of bounding element (ensuring `position` and `overflow: hidden`) and places the top-level QML DOM element **inside** the bounding element instead.
That allows to preserve the implicit sizing of the bounding `element` when needed, and QML element sizes are now be recalculated in runtime.
Bounding element size now always sets the top-level QML element `width` and `height` (instead of `implicitWidth` and `implicitHeight`), as it should.
Also the bounding element …

[Breaking] Wrap all root elements

---

src/engine/QMLEngine.js
src/modules/QtQuick/Text.js
tests/common.js

_Note: only the last commit does the stuff here, this is based on #367. Please see only that single commit that deals with Shadow DOM v1._
Shadow DOM v1 support is introduced, which allows us to hide and isolate the implementation so that it doesn't get affected by css styles.
It is used only when supported and is enabled by default, and could be disabled globally through `QmlWeb.useShadowDom` flag.
I could add the flag as an option to `QMLEngine`, but I don't see a specific usecase for that, so I decided not to overengineer. We could always introduce that flag as on option to `QMLEngine` constructor later, if needed (defaulting to `QmlWeb.useShadowDom`).
Fixes: https://github.com/qmlweb/qmlweb/issues/365
/cc @akreuzkamp @Plaristote @stephenmdangelo

QMLEngine: add Shadow DOM v1 for isolation

---

examples/customelement.html
examples/qml/main.qml
src/engine/CustomElements.js

This introduces support for registering QmlWeb based components as Custom Elements v1.
Refs:
* https://www.w3.org/TR/custom-elements/,
* https://developers.google.com/web/fundamentals/getting-started/primers/customelements.
One could now define QML Custom elements with the following call (given that the browser supports Custom Elements v1 or that a polyfill is loaded):
```js
QmlWeb.registerElement('qml-main', 'qml/main.qml');
```
And use them as:
```html
<qml-main width="300" height="300" color="red" firstName="World"></qml-main>
```
HTML attributes are constructed from the QML file, bound and dynamically updated, also updating HTML attributes has a direct effect on the QML state.
Example included, with a polyfill.
Caveat: atm, QmlWeb supports only one running engine, which limits the …

CustomElements: initial Custom Elements v1 support

---

src/modules/QtQuick/Loader.js
tests/failingTests.js

Fixes: https://github.com/qmlweb/qmlweb/issues/371
This works, I'm mostly sure that it was intended to be that way. Not 100%, though — I'm not very familiar with the contexts and scopes in QmlWeb.
It would be very nice if someone else could confirm this.
/cc @Plaristote @stephenmdangelo @akreuzkamp

Loader: fix children context

---

src/engine/modules.js

This happens with pre-parsed files, as "undefined" is serialized to "null"
via JSON.

loadImports: Handle moduleVersion being null

---

src/modules/QtQml/Qt.js

There probably isn't much sense in putting an actual underlying OS there,
as we don't support OS-specific features and don't have OS-specific
behaviour differences. It makes sense to distinguish browser platform
from all the other ones, though.
So it's set to 'qmlweb', as other values could be used by Qt QML.
Refs: http://doc.qt.io/qt-5/qml-qtqml-qt.html#platform-prop

Qt: add Qt.platform.os

---

AUTHORS

/cc @Gaubee, please check if this is the preferred name and email.
I extracted that from the b1157439a41f7aa21ccf5761a8d2ee2d539237a0 commit, but you could choose a different name/email if you wish to.

Add Gaubee to AUTHORS

---

src/engine/QMLProperty.js
src/qtbase/QColor.js
tests/Auto/QtQuick/tst_color.qml

When colors were modified using setter properties, that hack caused all
colors that were equal to the current one also being modified.
Breaking ==/=== that have an alternative of using Qt.colorEqual is
better than breaking color property setters.
/cc @Gaubee

QColor: remove comparable colors hack

---

README.md
bower.json
examples/customelement.html
examples/embed.html
examples/fullpage.html
gulpfile.js
karma.conf.js
src/engine/qmlstructure.js
tests/qmlweb.js

`qt.js` is still build for backwards compatibility for now.
Fixes: https://github.com/qmlweb/qmlweb/issues/380
/cc @qmlweb/collaborators

build: rename qt.js to qmlweb.js

---

src/engine/modules.js
src/modules/QtQuick/Animation.js

This ports `Animation` to the new module definition syntax to showcase my proposal in #260.
This is alternative to #261 and uses an even nicer syntax, but requires a ~~`stage-1`~~ `stage-2` transform to support [ES Class Fields & Static Properties](https://github.com/jeffmo/es-class-fields-and-static-properties) ~~`stage-1`~~ `stage-2` proposal. **Upd:** it's `stage-2` now.
`stage-2` means «The committee expects the feature to be developed and eventually included in the standard». See [TC39 Process](https://tc39.github.io/process-document/) for more info on that.
~~I doubt that we want this atm, perhaps we should wait until it reaches `stage-2` or `stage-3`.~~
Not sure if we want to adopt this on the current stage or if we should wait for it to reach `stage-3`, which could take some time. …

Animation: port to the new module definition syntax (stage-2 variant)

---

builder/shaker.js

Comparing subpaths with strings is not reliable, as Windows uses a different path separator.
Use `path.relative` instead and test for `'..'` inclusion.
Fixes: https://github.com/qmlweb/qmlweb/issues/432
/cc @bessorion — could you test if this (`windows-shaker`) branch works for you?

build: fix shaker on Windows platform

---

tests/QMLEngine/imports.js
tests/QMLEngine/qml/ImportQmldirSingleton.qml
tests/QMLEngine/qml/singleton/Style.qml
tests/QMLEngine/qml/singleton/qmldir
tests/failingTests.js

In accordance to http://doc.qt.io/qt-5/qtqml-modules-qmldir.html import statement can be declared as singleton. 
For now, this syntax is ignored and shows "unmatched" log message:
https://github.com/qmlweb/qmlweb/blob/9504d996a37cb8f50670b100b5cb51a2613edd7d/src/engine/import.js#L143
Added test covers #436

Added failingTest for qmldir singleton difinition support

---

src/modules/QtQuick/FontLoader.js

Tried to use FontLoader with FontLoader@0.0.2.
Found out that the name property wasn't filled and status was 2 ( Loading )
After debugging I found out that the FontLoader@0.0.2 library gives back a font object with the property family instead of a string containing fontFamily.

FontLoader.js gives back a font object

---

src/modules/QtQuick/Text.js

I added verticalAlignment to the Text Object. I've used table, table-cell and vertical-align in the css style properties.
That way it seems compatible with the most browsers.
It seems to work with fixed width and height, and with the use of anchors.
I think it also fixes #442

Added vertical align to Text

---

AUTHORS

/cc @wian007 — is that the preferred name and email?
Sorry for the delay on this.

doc: add Wian van Aggelen to AUTHORS
