AUTHORS

@Plaristote and Michael Martin Moro is the same person.

Remove a duplicate from AUTHORS

---

.travis.yml
README.md

Add .travis.yml and a Travis badge.

---

src/qtcore/qml/elements/QtQuick.Controls/Checkbox.js
src/qtcore/qml/elements/QtQuick.Controls/TextArea.js
src/qtcore/qml/elements/QtQuick/SequentialAnimation.js

add QMLFont constructor in Checkbox and TextArea
change permitted versions in TextArea
add QMLAnimation constructor in SequentialAnimation

Merge fork-arnopaehler (e20834e)

---

README.md

Everyone loves those!
Seriously — this helps us notice if we forget to publish a tagged release to npm, for example.

Readme: add npm, Bower, GitHub tag version badges

---

.gitignore
src/qtcore/qml/QMLBaseObject.js
src/qtcore/qml/QMLBinding.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/QObject.js
src/qtcore/qml/elements/Component.js
src/qtcore/qml/elements/Item.js
src/qtcore/qml/elements/QtQuick/Image.js
src/qtcore/qml/elements/QtQuick/Rectangle.js
src/qtcore/qml/elements/QtQuick/Repeater.js
src/qtcore/qml/elements/QtQuick/SequentialAnimation.js
src/qtcore/qml/elements/QtQuick/Text.js
src/qtcore/qml/lib/parser.js
src/qtcore/qml/qml.js
src/qtcore/qt.js

Merges a good deal of commits from kde-master to master.

Merge kde master

---

karma.conf.js
tests/QtQuick/Item.js
tests/QtQuick/Rectangle.js
tests/QtQuick/qml/ItemEmpty.qml
tests/QtQuick/qml/ItemSize.qml
tests/QtQuick/qml/RectangleColor.qml
tests/QtQuick/qml/RectangleTransparent.qml
tests/QtQuick/qml/RectangleWhite.qml
tests/common.js

This requires #50 and is based upon it, so that should land first.
This increases our tests coverage from 12.11% to ~~23.92%~~ 24.49%. =)

Add basic elements tests

---

tests/QMLEngine/bindings.js
tests/QMLEngine/javascript.js
tests/QMLEngine/properties.js
tests/QMLEngine/qml/BindingsUpdate.qml
tests/QMLEngine/qml/JavascriptBasicSyntax.qml
tests/QMLEngine/qml/PropertiesAlias.qml
tests/QMLEngine/qml/PropertiesBasic.qml
tests/QMLEngine/qml/ScopeLeaf.qml
tests/QMLEngine/qml/ScopeMid.qml
tests/QMLEngine/qml/ScopeRoot.qml
tests/QMLEngine/scope.js
tests/failingTests.js

Added more tests:
- test basic property types
- test aliased property
- test bindings immediate update
- test reference (grand)parents by id
the last test tries to reference a parent by its Id, but it fails with an error on the parser level.

Property tests

---

AUTHORS

Add Henrik Rudtrøm to AUTHORS

---

gulpfile.js

karma currently compresses the code under test, makes for bad stack traces...

remove code compression in karma

---

tests/Initialize/runner.js
tests/QMLEngine/qml/ScopeLeaf.qml
tests/common.js
tests/failingTests.js

Generates basic instantiation tests, can be used as template for further tests if the "//Generated" comment is removed. +5% coverage :)
depends on #63

Generated tests

---

tests/Render/Async/Image.qml
tests/Render/runner.js

This fixes the async Image render test, see #75.
/cc @henrikrudstrom @Plaristote

Image test fixes

---

karma.conf.js

This will give us the original sources and lines in the browser developer tools in the debug mode.
/cc @akreuzkamp @henrikrudstrom

tests: Serve qt.js.map from karma.

---

.travis.yml
gulpfile.js

~~Do not land, this is mostly for testing purposes for now.~~

travis: cache some directories to speed up the build

---

AUTHORS

Add Edwin Marshall to AUTHORS

---

tests/QtQuick/Timer.js
tests/QtQuick/qml/TimerSingleshot.qml
tests/common.js

Basic timer tests

---

tests/QMLEngine/qml/StateSimple.qml
tests/QMLEngine/qml/StateWhen.qml
tests/QMLEngine/states.js

Basic state tests

---

karma.conf.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/Component.js
src/qtcore/qml/lib/import.js
src/qtcore/qml/lib/parser.js
src/qtcore/qml/qml.js
src/qtcore/qt.js
tests/QMLEngine/imports.js
tests/QMLEngine/qml/ImportQmldir.qml
tests/QMLEngine/qml/somelib/RectangleColor.qml
tests/QMLEngine/qml/somelib/SimpleButton.qml
tests/QMLEngine/qml/somelib/qmldir

Started merging pavelvasev-fork, the file Import/Include code path mainly. 
Not tested and still some commits to go. 
Comments are welcome, especially from @pavelvasev

Merge pavelvasev import related commits

---

tests/QMLEngine/properties.js
tests/QMLEngine/qml/PropertiesAliasChanged.qml
tests/QMLEngine/qml/PropertiesAliasToId.qml
tests/QMLEngine/qml/PropertiesAliasToIdSameName.qml
tests/failingTests.js

case 1: alias to id - passing
case 2: alias to id with same name - failing
case 3: alias changed signal - failing
for case 3 see #aliassignals at #32

3 test cases for aliases

---

tests/QMLEngine/bindings.js
tests/QMLEngine/qml/BindingsRecursiveInit.qml
tests/QMLEngine/qml/BindingsRecursiveInit2.qml
tests/QMLEngine/qml/BindingsRecursiveInit3.qml
tests/QMLEngine/qml/BindingsRecursiveInit4.qml
tests/failingTests.js

@henrikrudstrom please note this PR

Test recursive property init

---

tests/QMLEngine/qml/ItemWithValue.qml
tests/QMLEngine/qml/ScopeSibling.qml
tests/QMLEngine/qml/ScopeUpflow.qml
tests/QMLEngine/qml/ScopeUpflowWithFoo.qml
tests/QMLEngine/qml/ScopeUpflowWithRealFoo.qml
tests/QMLEngine/scope.js

More scope tests

---

tests/Initialize/runner.js
tests/QMLEngine/bindings.js
tests/QMLEngine/imports.js
tests/QMLEngine/javascript.js
tests/QMLEngine/properties.js
tests/QMLEngine/scope.js
tests/QMLEngine/states.js
tests/QtQuick/Item.js
tests/QtQuick/Rectangle.js
tests/QtQuick/Timer.js
tests/common.js

Tests cleanup

---

tests/QMLEngine/bindings.js
tests/QMLEngine/qml/BindingsArray.qml

Blocked by #57. Adds a test that proves 91ef670 and 7bbea62 did the job.

adds tests to check arrays with bindings

---

tests/QtQuick/Timer.js

tests: lenient timer tests

---

src/qtcore/qml/QMLColor.js
src/qtcore/qml/elements/QtQuick.Controls/Checkbox.js
src/qtcore/qml/elements/QtQuick/Rectangle.js
src/qtcore/qml/elements/QtQuick/Text.js

merged 43c22d55f025da91a40864251261fac678d27fad#diff-7361786345720f04ae00796e6ceaea18L2527
compressed the onChanged statements to one line,
and added QMLColor to Checkbox.onColorChanged as well
@pavelvasev you ok with that?

Fix QMLColor function and Rectangle color handling

---

src/qtcore/qml/elements/QtQuick/TextInput.js

fix updateloop for textinput
(659f38103b4b72dc3d74c5dd0183fc0301db4531)

Uglybug fix of text input

---

src/qtcore/qml/elements/QtQuick.Controls/Checkbox.js

Checkbox bugfix

---

tests/QMLEngine/properties.js
tests/QMLEngine/qml/PropertiesChangedExpressionSignal.qml
tests/QMLEngine/qml/PropertiesChangedSignal.qml
tests/failingTests.js

/cc @Plaristote @henrikrudstrom

tests: Add property changed signal tests

---

AUTHORS

/cc @pavelvasev 
Also, please leave a comment at #52.

Add Pavel Vasev to AUTHORS.

---

tests/QMLEngine/imports.js
tests/QMLEngine/qml/ImportFrom/ImportMe.qml
tests/QMLEngine/qml/ImportFrom/ParentDir.qml
tests/QMLEngine/qml/ImportFrom/SiblingDir.qml
tests/QMLEngine/qml/ImportFromDir.qml
tests/QMLEngine/qml/ImportNoQmldir.qml

Some tests i wrote while debugging something else.

search path test and import tests, all green

---

src/qtcore/qml/QMLBaseObject.js
src/qtcore/qml/elements/Item.js
src/qtcore/qml/qml.js

This removes non-standard signals.
See https://github.com/qmlweb/qmlweb/pull/160#issuecomment-205872767 and discussion at 7d0ace1ea376de09988038fed69f1babbb306d2d.
/cc @akreuzkamp @Plaristote @pavelvasev

Remove non-standard signals

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/QtQuick.Controls/ComboBox.js
src/qtcore/qml/elements/QtQuick.Window/Screen.js
src/qtcore/qml/elements/QtQuick/Canvas.js
src/qtcore/qml/elements/QtQuick/Loader.js
src/qtcore/qt.js

For the new elements implemented by @arnopaehler (Loader, Screen, ComboBox) this should be considered as an initial implementation, we can fix all the issues later, so lets not hold the merges =). I fixed a few trivial issues, though (in separate commits).
The Screen implementation is not valid here (hence my TODO comment), but could serve as a good starting point.
Ref: #163

Merge some of arnopaehler patches

---

src/qtcore/qml/QMLBaseObject.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/Component.js

*Update: sorry, the descrption was from another PR at first.*
The source for this is 6022424e09f7692a664c1a31fa251ad2e0bd8514.
/cc @akreuzkamp, @Plaristote, @pavelvasev

Add support for attached properties.

---

gulpfile.js
src/qtcore/qml/QMLBaseObject.js
src/qtcore/qml/QMLEngine.js
src/qtcore/qml/elements/Component.js

Things went awry when I tried to merge this. When I rebased on master, it broke some tests.
I'll look at it soon, I'm just re-opening the pull request to make sure we don't forget this.
Original PR can be found here #160.

Add support for attached properties [re-opened]

---

.gitignore
src/qtcore/qml/elements/QtQuick.Controls/TextField.js
src/qtcore/qml/elements/QtQuick/TextEdit.js

This has TextEdit updates, TextField implementation, and minor gitignore changes.
Ref: #163

Merge the remaining arnopaehler patches

---

src/qtcore/qml/elements/QmlWeb.Dom/DomElement.js

This is aimed to replace #178 and 54de7de7efe82123c0ea38b49a5401e9681f7774 from #32.
/cc @pavelvasev, @Plaristote

QmlWeb.Dom: add DomElement stub

---

src/qtcore/font.js
src/qtcore/qml/QMLBinding.js
src/qtcore/qml/qml.js
src/qtcore/qt.js
tests/QMLEngine/basic.js
tests/QMLEngine/qml/BasicCreateQmlObject.qml

First bits of merge with kde-realinheritance, without the createProperty changes.

Merge kde realinheritance (split)

---

tests/QMLEngine/parse.js
tests/QMLEngine/qml/ParseSignal.qml

Improves our code coverage by testing the qmlsignaldef walker.

adds tests for the parser's ability to create signals

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/lib/import.js

This removes some unused code.
/cc @akreuzkamp, @Plaristote

Minor cleanup, remove some unused code

---

src/qtcore/qml/elements/QtQuick.Controls/Button.js

Extracted from 4c3bcc649447c07401a53677b801c937d03779bb.
Ref: #32.
/cc @pavelvasev @Plaristote @akreuzkamp

@pavelvasev merge: Button: implement 'enabled' property

---

tests/QMLEngine/qml/ScopeOverride.qml
tests/QMLEngine/qml/ScopeOverrideBase.qml
tests/QMLEngine/scope.js
tests/failingTests.js

test case for bbcf79f and
https://github.com/qmlweb/qmlweb/issues/32#issuecomment-190834951 topic
`context`

failing test case for scope

---

AUTHORS

Add Harsh Choudhary to AUTHORS

---

AUTHORS

Add Igor Andruszkiewicz to AUTHORS

---

src/qtcore/qml/QMLEngine.js
src/qtcore/qml/lib/parser.js
src/qtcore/qt.js

This is a cherry-pick of bae9d88, ref: #32.
/cc @pavelvasev

@pavelvasev merge: keep file path information in exceptions during qml parse

---

src/qtcore/qml/elements/QtQuick/ListModel.js

This is a cherry-pick of 04bd0b18bba2d13ef635f37788f29483358415b9, ref: #32.
This commit says:
> by Alexander Potashev
@pavelvasev, is this a commit by @aspotashev or someone else? Guessing by name and some kde-related activity.
Who should be set as the author of this commit?
/cc @Plaristote, @akreuzkamp — the change itself is trivial here, hoping for a quick review. This does LGTM, but it would be good if any of you could also take a look =).

@pavelvasev merge: ListModel: Notify dependent properties about list element changes

---

AUTHORS

/cc @aspotashev, could you please check that I got your preferred name and email correct?

Add Alexander Potashev to AUTHORS

---

tests/QMLEngine/qml/BindingsArray.qml
tests/QMLEngine/qml/BindingsUpdate.qml
tests/QMLEngine/qml/ItemWithValue.qml
tests/QMLEngine/qml/JavascriptBasicSyntax.qml
tests/QMLEngine/qml/JavascriptRegexp.qml
tests/QMLEngine/qml/PropertiesAlias.qml
tests/QMLEngine/qml/PropertiesBasic.qml
tests/QMLEngine/qml/ScopeLeaf.qml
tests/QMLEngine/qml/ScopeMid.qml
tests/QMLEngine/qml/ScopeRoot.qml

This is a trivial change.
Though, this is needed to fix Item placement and inheritance and for further fixes in #200.
Hoping for a quick review here.

tests: Do not forget 'import QtQuick'

---

tests/Initialize/runner.js

This just adds more basic initialization tests for the elements that we have.
5% more (basic) coverage.

tests: Add more initialize tests

---

src/qtcore/qml/elements/Item.js
tests/Initialize/runner.js

This merges commit af7f263, ref: #223.
Not sure if we want this, but it's not used anywhere expect for being checked in the tests (that check is also removed here).
/cc @igosoft, @akreuzkamp, @Plaristote.

@igosoft merge: Remove this.dom.qml property

---

.travis.yml
README.md

This is a work in progress, do not review yet.
Fixes  #136.

travis: Report code coverage to codecov.io

---

src/qtcore/qml/qml.js

It's 2016 on my calendar :wink:.
This removes some fallback code from 2012 by @lpaimen.
`Object.defineProperty` is supported by all ES5 browsers, see http://caniuse.com/es5 for those.
Also see https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Browser_compatibility.

Use Object.defineProperty on all browsers

---

src/modules/QtQuick/TextEdit.js

Extracted from dce7d96575a11ffb1b06e048f6531000c6e56479, ref: #32.
/cc @pavelvasev

@pavelvasev merge: TextEdit: set textarea padding to 0

---

src/qtcore/qml/QMLEngine.js

This is a cherry-pick of 6c062ec.
/cc @igosoft @Plaristote @akreuzkamp @pavelvasev 
Ref: #128, #62.

@igosoft merge: QMLEngine: allow to specify parentComponent in loadQMLTree

---

src/modules/QtQuick/Item.js

This merges commit 31afc1f9ba2286adaddb5559b89201b4fcb86bff, ref: #223.
/cc @igosoft

@igosoft merge: Item parent fixes

---

src/modules/QtQuick/Loader.js

This merges commit 6b7593a, ref: #223.
Could depend on #246 and #244.
/cc @igosoft

@igosoft merge: Update Loader

---

src/qtcore/qml/qml.js
src/qtcore/qt.js
tests/QMLEngine/qml/ScopeIdOverProperty.qml
tests/QMLEngine/qml/ScopeIdOverPropertyImpl.qml
tests/QMLEngine/scope.js

Going over pavelvasev's branch, I'm trying to merge the [context] category.
There's one thing I'm not sure about. The setupGetterSetter change: I do not know what it does, if you can set me up to speed with that @pavelvasev ?

some bugfixes on context

---

tests/QtQuick/ListModel.js
tests/QtQuick/qml/ListModel.qml

Add tests to ListModel

---

AUTHORS

Add Stephen D'Angelo to AUTHORS

---

src/modules/QtQuick/Repeater.js

This merges commit f5079446c8808a0133492c595a89646ff621bcdd, ref: #223.
/cc @igosoft

@igosoft merge: Repeater updates

---

src/modules/QtQuick/Animation.js
src/qtcore/qml.js

This ports `Animation` to the new module definition syntax to showcase my proposal in #260.
/cc @Plaristote @akreuzkamp

Animation: port to the new module definition syntax

---

docs/JSItemModel.md
package.json
src/qtbase/JSItemModel.js

* Convert JSItemModel to class.
* Move JSItemModel documentation to `docs/` folder.
/cc @akreuzkamp @Plaristote 
This PR creates a `docs/` folder =).

JSItemModel: initial cleanup

---

docs/QMLEngine.md
gulpfile.js
src/engine/QMLEngine.js
src/engine/QmlWeb.js

~~Not finished yet.~~
@akreuzkamp, @Plaristote, could you take a quick look at the direction where this is going?
This still needs some comments cleanup and minor code cleanup, which I will doo soon.

Cleanup QMLEngine

---

AUTHORS

@hhaveri, could you confirm that this is the preferred name spelling and email address?

Add Heikki Haveri to AUTHORS

---

src/modules/QtQuick/MouseArea.js

Parts of MouseArea got broken in commit 9b1d2bbee6993fd29d4ebf46ac4be2a43695d65c

MouseArea: fix hover & clicked events

---

AUTHORS

Add Alexander Rössler to AUTHORS

---

src/modules/QtQuick/SystemPalette.js

SystemPalette: make it actually work

---

src/modules/QtQuick/MouseArea.js

The "mousemove" DOM event is only sent to the MouseArea's DOM element while
the cursor remains over the DOM element. This now attaches a temporary
event listener to "document" and translates the JavaScript MouseEvent
"clientX" and "clientY" properties to the MouseArea's coordinate space
(In regards to CSS transformations, this only takes into account translate
and scale transformations).

QtQuick/MouseArea: Emit positionChanged when pressed & cursor moves outside

---

src/modules/QtTest/TestCase.js
tests/Auto/QtTest/tst_Math.qml
tests/Auto/runner.js
tests/Initialize/runner.js
tests/QtTest/TestCase.js
tests/QtTest/qml/TestCaseDatadriven.qml
tests/QtTest/qml/TestCaseEmpty.qml
tests/QtTest/qml/TestCaseSimple.qml

This adds `TestCase` element.
I will get more methods ready before merging.

TestCase: implement QtTest.TestCase

---

src/modules/QtGraphicalEffects/RectangularGlow.js
src/modules/QtQml/Qt.js
src/modules/QtQuick.Controls/CheckBox.js
src/modules/QtQuick.Window/Window.js
src/modules/QtQuick/Rectangle.js
src/modules/QtQuick/Text.js
src/modules/QtQuick/TextEdit.js
src/qtbase/QColor.js
tests/Auto/QtQuick/tst_color.qml
tests/QMLEngine/basic.js
tests/QMLEngine/imports.js
tests/QtBase/QColor.js
tests/QtQuick/Rectangle.js

This implements toString that returns results similar to what Qt QML does.
Also, Qt.hsla() and Qt.hsva() methods were fixed to return a QColor.
Css color specification is now received as .$css property.
New testcases are included.
/cc @Gaubee, @stephenmdangelo

QColor: complete implementation

---

README.md

This adds a section to link users to related efforts so that they could choose the best suited approach for their usecase.
/cc @labsin, @seniorivn, @vkrv, @joeblew99.
Refs: https://github.com/qmlweb/qmlweb/issues/398#issuecomment-287621587, #401.

Readme: add 'Related efforts' section

---

src/modules/QtQuick/TextEdit.js

Hello, thank you for your project!
Looks like my changes adding readonly option support for TextEdit's textarea. Feel free to correct me.

TextEdit readonly property initial support

---

AUTHORS

/cc @a-andreyev, please review.
Is this the preferred name and email?

Add Alexey Andreyev to AUTHORS

---

karma.conf.js
src/engine/properties.js
src/modules/QtQuick.Controls/ComboBox.js
src/modules/QtQuick.Controls/ScrollView.js
src/modules/QtQuick/Column.js
src/modules/QtQuick/Item.js
src/modules/QtQuick/MouseArea.js
src/modules/QtQuick/Positioner.js
src/modules/QtQuick/Row.js
src/qtbase/Signal.js
tests/QMLEngine/basepath/B.qml
tests/QMLEngine/basepath/import/A.qml
tests/QMLEngine/basepath/test.js
tests/QMLEngine/basepath/test.qml
tests/QtQuick.Controls/ComboBox/test.js
tests/QtQuick.Controls/ComboBox/test.qml
tests/QtQuick.Controls/ComboBox/test_populated.qml

April fixes

---

AUTHORS

Ref: https://github.com/qmlweb/qmlweb/pull/437
/cc @bessorion — could you confirm that the data is correct?

Add Yauhen Kotau to AUTHORS
